# Generated by Django 2.2.9 on 2020-05-06 07:46

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(blank=True, max_length=100)),
                ('user_lastname', models.CharField(blank=True, max_length=100)),
                ('user_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('user_mobile', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('user_sex', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
