# Generated by Django 2.2.9 on 2020-05-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_sex',
            new_name='sex',
        ),
    ]
